[local]
appUrl = 'http://localhost:5173'

[local.server]
port = 3001

[local.cors]
origins = ['http://localhost:5173']

[local.db]
maxConnections = 5
ssl = false

[deployed]
appUrl = 'https://ts-template.coji-dev.com'

[deployed.server]
port = 3001

[deployed.cors]
origins = ['https://ts-template.coji-dev.com']

[deployed.db]
maxConnections = 10
ssl = false
