name: ts_template

services:
  postgres:
    image: postgres:18.1
    restart: always
    container_name: ts-template-db
    environment:
      POSTGRES_USER: ts_template
      POSTGRES_PASSWORD: ts_template
      POSTGRES_DB: ts_template
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./packages/db/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

volumes:
  pgdata: